### PR TITLE
Update Japanese translations

### PR DESCRIPTION
**Pull request by HiSubway**

### CODE REVIEW

**Review by sheikhhaziq — CHANGES_REQUESTED** [review]
After translating from google some words such as medium does not refer to medium. check these things first

**Review by sheikhhaziq — APPROVED** [review]

**Comment by HiSubway** [comment]
That is the correct translation. In Japanese, '中' means "medium", "inside" and "during".



Thank you for merging.

**Comment by HiSubway** [comment]
Thank you for merging!

**Comment by sheikhhaziq** [comment]
Contributions are always welcome. I look forward for more contributions from you.

**Pull request merged**
